//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FlightManagementDesktop.InsertSale {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Response", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Response : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private bool ResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultDescriptionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public bool Result {
            get {
                return this.ResultField;
            }
            set {
                if ((this.ResultField.Equals(value) != true)) {
                    this.ResultField = value;
                    this.RaisePropertyChanged("Result");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string ResultDescription {
            get {
                return this.ResultDescriptionField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultDescriptionField, value) != true)) {
                    this.ResultDescriptionField = value;
                    this.RaisePropertyChanged("ResultDescription");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Customer", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Customer : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Travel", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Travel : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int CodeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string OriginField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DestinationField;
        
        private System.DateTime Time_DepartureField;
        
        private System.DateTime Time_ArrivedField;
        
        private FlightManagementDesktop.InsertSale.TimeSpan DurationField;
        
        private int MaxCapacityField;
        
        private int MaxRowField;
        
        private int MaxSeatsRowField;
        
        private int CompanyIDField;
        
        private bool StatusField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CompanyNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string Origin_DestinationField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Code {
            get {
                return this.CodeField;
            }
            set {
                if ((this.CodeField.Equals(value) != true)) {
                    this.CodeField = value;
                    this.RaisePropertyChanged("Code");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Origin {
            get {
                return this.OriginField;
            }
            set {
                if ((object.ReferenceEquals(this.OriginField, value) != true)) {
                    this.OriginField = value;
                    this.RaisePropertyChanged("Origin");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Destination {
            get {
                return this.DestinationField;
            }
            set {
                if ((object.ReferenceEquals(this.DestinationField, value) != true)) {
                    this.DestinationField = value;
                    this.RaisePropertyChanged("Destination");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.DateTime Time_Departure {
            get {
                return this.Time_DepartureField;
            }
            set {
                if ((this.Time_DepartureField.Equals(value) != true)) {
                    this.Time_DepartureField = value;
                    this.RaisePropertyChanged("Time_Departure");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public System.DateTime Time_Arrived {
            get {
                return this.Time_ArrivedField;
            }
            set {
                if ((this.Time_ArrivedField.Equals(value) != true)) {
                    this.Time_ArrivedField = value;
                    this.RaisePropertyChanged("Time_Arrived");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, EmitDefaultValue=false, Order=5)]
        public FlightManagementDesktop.InsertSale.TimeSpan Duration {
            get {
                return this.DurationField;
            }
            set {
                if ((object.ReferenceEquals(this.DurationField, value) != true)) {
                    this.DurationField = value;
                    this.RaisePropertyChanged("Duration");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=6)]
        public int MaxCapacity {
            get {
                return this.MaxCapacityField;
            }
            set {
                if ((this.MaxCapacityField.Equals(value) != true)) {
                    this.MaxCapacityField = value;
                    this.RaisePropertyChanged("MaxCapacity");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=7)]
        public int MaxRow {
            get {
                return this.MaxRowField;
            }
            set {
                if ((this.MaxRowField.Equals(value) != true)) {
                    this.MaxRowField = value;
                    this.RaisePropertyChanged("MaxRow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=8)]
        public int MaxSeatsRow {
            get {
                return this.MaxSeatsRowField;
            }
            set {
                if ((this.MaxSeatsRowField.Equals(value) != true)) {
                    this.MaxSeatsRowField = value;
                    this.RaisePropertyChanged("MaxSeatsRow");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=9)]
        public int CompanyID {
            get {
                return this.CompanyIDField;
            }
            set {
                if ((this.CompanyIDField.Equals(value) != true)) {
                    this.CompanyIDField = value;
                    this.RaisePropertyChanged("CompanyID");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=10)]
        public bool Status {
            get {
                return this.StatusField;
            }
            set {
                if ((this.StatusField.Equals(value) != true)) {
                    this.StatusField = value;
                    this.RaisePropertyChanged("Status");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=11)]
        public string CompanyName {
            get {
                return this.CompanyNameField;
            }
            set {
                if ((object.ReferenceEquals(this.CompanyNameField, value) != true)) {
                    this.CompanyNameField = value;
                    this.RaisePropertyChanged("CompanyName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=12)]
        public string Origin_Destination {
            get {
                return this.Origin_DestinationField;
            }
            set {
                if ((object.ReferenceEquals(this.Origin_DestinationField, value) != true)) {
                    this.Origin_DestinationField = value;
                    this.RaisePropertyChanged("Origin_Destination");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="TimeSpan", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class TimeSpan : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="Seats", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class Seats : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int RowField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SeatField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string FullField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Row {
            get {
                return this.RowField;
            }
            set {
                if ((this.RowField.Equals(value) != true)) {
                    this.RowField = value;
                    this.RaisePropertyChanged("Row");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Seat {
            get {
                return this.SeatField;
            }
            set {
                if ((object.ReferenceEquals(this.SeatField, value) != true)) {
                    this.SeatField = value;
                    this.RaisePropertyChanged("Seat");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Full {
            get {
                return this.FullField;
            }
            set {
                if ((object.ReferenceEquals(this.FullField, value) != true)) {
                    this.FullField = value;
                    this.RaisePropertyChanged("Full");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="InsertSale.InsertSaleSoap")]
    public interface InsertSaleSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parSeat del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/SaleRequest", ReplyAction="*")]
        FlightManagementDesktop.InsertSale.SaleRequestResponse SaleRequest(FlightManagementDesktop.InsertSale.SaleRequestRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetCustomerResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetCustomer", ReplyAction="*")]
        FlightManagementDesktop.InsertSale.GetCustomerResponse GetCustomer(FlightManagementDesktop.InsertSale.GetCustomerRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetTravelResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTravel", ReplyAction="*")]
        FlightManagementDesktop.InsertSale.GetTravelResponse GetTravel(FlightManagementDesktop.InsertSale.GetTravelRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetTravelSelectedResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTravelSelected", ReplyAction="*")]
        FlightManagementDesktop.InsertSale.GetTravelSelectedResponse GetTravelSelected(FlightManagementDesktop.InsertSale.GetTravelSelectedRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetSeatsResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetSeats", ReplyAction="*")]
        FlightManagementDesktop.InsertSale.GetSeatsResponse GetSeats(FlightManagementDesktop.InsertSale.GetSeatsRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaleRequestRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaleRequest", Namespace="http://tempuri.org/", Order=0)]
        public FlightManagementDesktop.InsertSale.SaleRequestRequestBody Body;
        
        public SaleRequestRequest() {
        }
        
        public SaleRequestRequest(FlightManagementDesktop.InsertSale.SaleRequestRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaleRequestRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int parRow;
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=1)]
        public string parSeat;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=2)]
        public int parTravel;
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=3)]
        public int parCustomer;
        
        public SaleRequestRequestBody() {
        }
        
        public SaleRequestRequestBody(int parRow, string parSeat, int parTravel, int parCustomer) {
            this.parRow = parRow;
            this.parSeat = parSeat;
            this.parTravel = parTravel;
            this.parCustomer = parCustomer;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class SaleRequestResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="SaleRequestResponse", Namespace="http://tempuri.org/", Order=0)]
        public FlightManagementDesktop.InsertSale.SaleRequestResponseBody Body;
        
        public SaleRequestResponse() {
        }
        
        public SaleRequestResponse(FlightManagementDesktop.InsertSale.SaleRequestResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class SaleRequestResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FlightManagementDesktop.InsertSale.Response SaleRequestResult;
        
        public SaleRequestResponseBody() {
        }
        
        public SaleRequestResponseBody(FlightManagementDesktop.InsertSale.Response SaleRequestResult) {
            this.SaleRequestResult = SaleRequestResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomer", Namespace="http://tempuri.org/", Order=0)]
        public FlightManagementDesktop.InsertSale.GetCustomerRequestBody Body;
        
        public GetCustomerRequest() {
        }
        
        public GetCustomerRequest(FlightManagementDesktop.InsertSale.GetCustomerRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetCustomerRequestBody {
        
        public GetCustomerRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetCustomerResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetCustomerResponse", Namespace="http://tempuri.org/", Order=0)]
        public FlightManagementDesktop.InsertSale.GetCustomerResponseBody Body;
        
        public GetCustomerResponse() {
        }
        
        public GetCustomerResponse(FlightManagementDesktop.InsertSale.GetCustomerResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetCustomerResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FlightManagementDesktop.InsertSale.Customer[] GetCustomerResult;
        
        public GetCustomerResponseBody() {
        }
        
        public GetCustomerResponseBody(FlightManagementDesktop.InsertSale.Customer[] GetCustomerResult) {
            this.GetCustomerResult = GetCustomerResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTravelRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTravel", Namespace="http://tempuri.org/", Order=0)]
        public FlightManagementDesktop.InsertSale.GetTravelRequestBody Body;
        
        public GetTravelRequest() {
        }
        
        public GetTravelRequest(FlightManagementDesktop.InsertSale.GetTravelRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetTravelRequestBody {
        
        public GetTravelRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTravelResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTravelResponse", Namespace="http://tempuri.org/", Order=0)]
        public FlightManagementDesktop.InsertSale.GetTravelResponseBody Body;
        
        public GetTravelResponse() {
        }
        
        public GetTravelResponse(FlightManagementDesktop.InsertSale.GetTravelResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTravelResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FlightManagementDesktop.InsertSale.Travel[] GetTravelResult;
        
        public GetTravelResponseBody() {
        }
        
        public GetTravelResponseBody(FlightManagementDesktop.InsertSale.Travel[] GetTravelResult) {
            this.GetTravelResult = GetTravelResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTravelSelectedRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTravelSelected", Namespace="http://tempuri.org/", Order=0)]
        public FlightManagementDesktop.InsertSale.GetTravelSelectedRequestBody Body;
        
        public GetTravelSelectedRequest() {
        }
        
        public GetTravelSelectedRequest(FlightManagementDesktop.InsertSale.GetTravelSelectedRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTravelSelectedRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int parCode;
        
        public GetTravelSelectedRequestBody() {
        }
        
        public GetTravelSelectedRequestBody(int parCode) {
            this.parCode = parCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTravelSelectedResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTravelSelectedResponse", Namespace="http://tempuri.org/", Order=0)]
        public FlightManagementDesktop.InsertSale.GetTravelSelectedResponseBody Body;
        
        public GetTravelSelectedResponse() {
        }
        
        public GetTravelSelectedResponse(FlightManagementDesktop.InsertSale.GetTravelSelectedResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTravelSelectedResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FlightManagementDesktop.InsertSale.Travel GetTravelSelectedResult;
        
        public GetTravelSelectedResponseBody() {
        }
        
        public GetTravelSelectedResponseBody(FlightManagementDesktop.InsertSale.Travel GetTravelSelectedResult) {
            this.GetTravelSelectedResult = GetTravelSelectedResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSeatsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeats", Namespace="http://tempuri.org/", Order=0)]
        public FlightManagementDesktop.InsertSale.GetSeatsRequestBody Body;
        
        public GetSeatsRequest() {
        }
        
        public GetSeatsRequest(FlightManagementDesktop.InsertSale.GetSeatsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSeatsRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int parCode;
        
        public GetSeatsRequestBody() {
        }
        
        public GetSeatsRequestBody(int parCode) {
            this.parCode = parCode;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetSeatsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetSeatsResponse", Namespace="http://tempuri.org/", Order=0)]
        public FlightManagementDesktop.InsertSale.GetSeatsResponseBody Body;
        
        public GetSeatsResponse() {
        }
        
        public GetSeatsResponse(FlightManagementDesktop.InsertSale.GetSeatsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetSeatsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public FlightManagementDesktop.InsertSale.Seats[] GetSeatsResult;
        
        public GetSeatsResponseBody() {
        }
        
        public GetSeatsResponseBody(FlightManagementDesktop.InsertSale.Seats[] GetSeatsResult) {
            this.GetSeatsResult = GetSeatsResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface InsertSaleSoapChannel : FlightManagementDesktop.InsertSale.InsertSaleSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class InsertSaleSoapClient : System.ServiceModel.ClientBase<FlightManagementDesktop.InsertSale.InsertSaleSoap>, FlightManagementDesktop.InsertSale.InsertSaleSoap {
        
        public InsertSaleSoapClient() {
        }
        
        public InsertSaleSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public InsertSaleSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsertSaleSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public InsertSaleSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightManagementDesktop.InsertSale.SaleRequestResponse FlightManagementDesktop.InsertSale.InsertSaleSoap.SaleRequest(FlightManagementDesktop.InsertSale.SaleRequestRequest request) {
            return base.Channel.SaleRequest(request);
        }
        
        public FlightManagementDesktop.InsertSale.Response SaleRequest(int parRow, string parSeat, int parTravel, int parCustomer) {
            FlightManagementDesktop.InsertSale.SaleRequestRequest inValue = new FlightManagementDesktop.InsertSale.SaleRequestRequest();
            inValue.Body = new FlightManagementDesktop.InsertSale.SaleRequestRequestBody();
            inValue.Body.parRow = parRow;
            inValue.Body.parSeat = parSeat;
            inValue.Body.parTravel = parTravel;
            inValue.Body.parCustomer = parCustomer;
            FlightManagementDesktop.InsertSale.SaleRequestResponse retVal = ((FlightManagementDesktop.InsertSale.InsertSaleSoap)(this)).SaleRequest(inValue);
            return retVal.Body.SaleRequestResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightManagementDesktop.InsertSale.GetCustomerResponse FlightManagementDesktop.InsertSale.InsertSaleSoap.GetCustomer(FlightManagementDesktop.InsertSale.GetCustomerRequest request) {
            return base.Channel.GetCustomer(request);
        }
        
        public FlightManagementDesktop.InsertSale.Customer[] GetCustomer() {
            FlightManagementDesktop.InsertSale.GetCustomerRequest inValue = new FlightManagementDesktop.InsertSale.GetCustomerRequest();
            inValue.Body = new FlightManagementDesktop.InsertSale.GetCustomerRequestBody();
            FlightManagementDesktop.InsertSale.GetCustomerResponse retVal = ((FlightManagementDesktop.InsertSale.InsertSaleSoap)(this)).GetCustomer(inValue);
            return retVal.Body.GetCustomerResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightManagementDesktop.InsertSale.GetTravelResponse FlightManagementDesktop.InsertSale.InsertSaleSoap.GetTravel(FlightManagementDesktop.InsertSale.GetTravelRequest request) {
            return base.Channel.GetTravel(request);
        }
        
        public FlightManagementDesktop.InsertSale.Travel[] GetTravel() {
            FlightManagementDesktop.InsertSale.GetTravelRequest inValue = new FlightManagementDesktop.InsertSale.GetTravelRequest();
            inValue.Body = new FlightManagementDesktop.InsertSale.GetTravelRequestBody();
            FlightManagementDesktop.InsertSale.GetTravelResponse retVal = ((FlightManagementDesktop.InsertSale.InsertSaleSoap)(this)).GetTravel(inValue);
            return retVal.Body.GetTravelResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightManagementDesktop.InsertSale.GetTravelSelectedResponse FlightManagementDesktop.InsertSale.InsertSaleSoap.GetTravelSelected(FlightManagementDesktop.InsertSale.GetTravelSelectedRequest request) {
            return base.Channel.GetTravelSelected(request);
        }
        
        public FlightManagementDesktop.InsertSale.Travel GetTravelSelected(int parCode) {
            FlightManagementDesktop.InsertSale.GetTravelSelectedRequest inValue = new FlightManagementDesktop.InsertSale.GetTravelSelectedRequest();
            inValue.Body = new FlightManagementDesktop.InsertSale.GetTravelSelectedRequestBody();
            inValue.Body.parCode = parCode;
            FlightManagementDesktop.InsertSale.GetTravelSelectedResponse retVal = ((FlightManagementDesktop.InsertSale.InsertSaleSoap)(this)).GetTravelSelected(inValue);
            return retVal.Body.GetTravelSelectedResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        FlightManagementDesktop.InsertSale.GetSeatsResponse FlightManagementDesktop.InsertSale.InsertSaleSoap.GetSeats(FlightManagementDesktop.InsertSale.GetSeatsRequest request) {
            return base.Channel.GetSeats(request);
        }
        
        public FlightManagementDesktop.InsertSale.Seats[] GetSeats(int parCode) {
            FlightManagementDesktop.InsertSale.GetSeatsRequest inValue = new FlightManagementDesktop.InsertSale.GetSeatsRequest();
            inValue.Body = new FlightManagementDesktop.InsertSale.GetSeatsRequestBody();
            inValue.Body.parCode = parCode;
            FlightManagementDesktop.InsertSale.GetSeatsResponse retVal = ((FlightManagementDesktop.InsertSale.InsertSaleSoap)(this)).GetSeats(inValue);
            return retVal.Body.GetSeatsResult;
        }
    }
}
